// <auto-generated />
using System;
using Bugify.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bugify.API.Migrations
{
    [DbContext(typeof(BugifyDbContext))]
    [Migration("20251105191014_ReplaceTaskProgress")]
    partial class ReplaceTaskProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bugify.API.Models.Domain.AddTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProgressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProgressId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Bugify.API.Models.Domain.TaskProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskProgresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("759c64cb-9639-4218-bd6f-e68718429075"),
                            Name = "NotStarted"
                        },
                        new
                        {
                            Id = new Guid("915ea79b-f8fa-4f1a-bf02-e9d73faf14a6"),
                            Name = "InProgress"
                        },
                        new
                        {
                            Id = new Guid("852a80bb-a5d1-4ebd-8959-c115a0ddee68"),
                            Name = "Completed"
                        },
                        new
                        {
                            Id = new Guid("c99a883d-51e3-4738-9ee6-c6ad53d73b37"),
                            Name = "OnHold"
                        },
                        new
                        {
                            Id = new Guid("86704552-8451-4916-8494-b0dfd3490f44"),
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("Bugify.API.Models.Domain.AddTask", b =>
                {
                    b.HasOne("Bugify.API.Models.Domain.TaskProgress", "Progress")
                        .WithMany()
                        .HasForeignKey("ProgressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Progress");
                });
#pragma warning restore 612, 618
        }
    }
}
